<script setup lang="ts">
const config = useRuntimeConfig()
const siteUrl = `https://${config.public.domain || 'launchlog.ai'}`
const pageUrl = `${siteUrl}/privacy`
const updated = 'September 1, 2026'
const legalName = config.public.legalName.trim()
const legalEmail = config.public.legalEmail.trim()
const description
  = 'How LaunchLog processes personal data for listings, accounts, payments, support and service operation, and the rights you have over it.'

const sections = [
  {
    id: 'overview',
    title: 'Overview',
    blocks: [
      { type: 'p', text: legalName ? `${legalName} operates the LaunchLog service at launchlog.ai. This policy explains what personal data the service processes, why, on what legal basis, and the choices you have.` : 'LaunchLog is the service available at launchlog.ai. The legal operator name is not currently configured for display. This policy explains what personal data the service processes, why, on what legal basis, and the choices you have.' },
      { type: 'p', text: 'We keep data collection deliberately narrow. We do not buy, sell or rent personal data. Optional analytics and Meta advertising measurement remain off until you choose to enable them.' },
    ],
  },
  {
    id: 'data-we-collect',
    title: 'Information we collect',
    blocks: [
      { type: 'subhead', text: 'Information you provide' },
      { type: 'list', items: [
        'Account data: email address and authentication identifier when you sign in (handled by Firebase Authentication).',
        'Listing data: the product URL, name, tagline, description, category and contact email you submit or edit for a listing or free preview.',
        'Newsletter data: the email address you voluntarily submit and the public LaunchLog surface where you submitted it.',
        'Billing data: name and billing details required to process a subscription. Card numbers are entered directly with Stripe and never reach our servers.',
        'Correspondence: messages you send to our support, legal or DMCA addresses.',
      ] },
      { type: 'subhead', text: 'Information collected automatically' },
      { type: 'list', items: [
        'Public metadata fetched from the URL you submit (title, meta description, OpenGraph data, favicon, screenshot) to build your listing preview.',
        'Request and operational log data generated by the application and infrastructure providers for security, abuse prevention and reliability.',
        'Optional aggregate analytics: after you accept analytics, LaunchLog sends approved public pageviews and the four funnel event names to our self-hosted Plausible endpoint. Private preview URLs, tokens, Stripe Session IDs, Reddit click IDs and arbitrary query values are blocked.',
        'Optional advertising measurement: after you separately accept it, Meta Pixel measures approved public pageviews and Meta Conversions API receives approved funnel event names, an opaque event ID, browser and request data, and Meta advertising-cookie values when present. Private preview tokens, Stripe Session IDs and submitted product content are not sent.',
      ] },
    ],
  },
  {
    id: 'how-we-use',
    title: 'How we use information',
    blocks: [
      { type: 'list', items: [
        'To create, enrich and publish listings and previews, and to apply administrator moderation actions when required.',
        'To authenticate you and protect your account.',
        'To process subscriptions, present receipt facts and handle approved refunds manually in Stripe.',
        'To respond to support, legal and takedown requests.',
        'To keep the service secure, prevent spam and abuse, and improve the product.',
        'With your consent, to measure whether LaunchLog advertising leads to previews, checkout starts and published listings, and to improve campaign delivery.',
        'To send the transactional listing-access email after a paid listing is created.',
        'To request double opt-in newsletter enrollment when you explicitly submit the newsletter form. Newsletter subscription is voluntary and separate from checkout.',
      ] },
    ],
  },
  {
    id: 'legal-bases',
    title: 'Legal bases (GDPR)',
    blocks: [
      { type: 'p', text: 'Where the GDPR applies, we rely on the following legal bases:' },
      { type: 'list', items: [
        'Contract — to provide listings, accounts and paid subscriptions you request.',
        'Legitimate interests — to secure the service, prevent abuse and maintain a useful, spam-free directory, balanced against your rights.',
        'Legal obligation — to keep transaction and tax records.',
        'Consent — separately for optional aggregate analytics, optional Meta advertising measurement and any optional communications. You can withdraw either browser choice at any time through Privacy choices in the footer.',
      ] },
    ],
  },
  {
    id: 'processors',
    title: 'Sharing and processors',
    blocks: [
      { type: 'p', text: 'We use third-party service providers to operate LaunchLog. We do not sell personal data. Current providers include:' },
      { type: 'list', items: [
        'Stripe — payments and subscription billing.',
        'Firebase Authentication (Google) — sign-in and identity.',
        'Railway — application hosting and the PostgreSQL database.',
        'Cloudflare — DNS, CDN, asset storage (R2) and security.',
        'Microlink — website screenshot and metadata capture for previews.',
        'Resend — transactional email delivery.',
        'Beehiiv — optional newsletter double opt-in, consent status, delivery, unsubscribe and suppression. LaunchLog sends the submitted address and surface source server-to-server.',
        'Plausible — self-hosted aggregate analytics, used only after your analytics choice.',
        'Meta Platforms — advertising measurement through Meta Pixel and Conversions API, used only after your advertising-measurement choice.',
      ] },
      { type: 'p', text: 'We may also disclose information where required by law or to protect our rights, our users and the safety of the service.' },
    ],
  },
  {
    id: 'retention',
    title: 'Data retention',
    blocks: [
      { type: 'list', items: [
        'Free previews are private, excluded from search, and stop being available through the active-preview endpoint after 7 days.',
        'Published listing content remains while your listing is active and may persist in caches and AI/search indexes outside our control after removal.',
        'Account, subscription and payment-reference records are kept while needed to provide the Service and meet applicable accounting or legal obligations.',
        'Operational logs are retained according to the configured application and infrastructure-provider settings.',
        'LaunchLog does not keep a local newsletter subscriber ledger. Beehiiv retains consent, unsubscribe and suppression records under its configured service terms.',
        'Your analytics and advertising-measurement choices expire after six months. Rejecting or withdrawing stops future requests for that optional purpose; withdrawing advertising consent also removes the Meta Pixel and expires the LaunchLog-domain Meta advertising cookies we can access.',
      ] },
    ],
  },
  {
    id: 'your-rights',
    title: 'Your rights',
    blocks: [
      { type: 'p', text: legalEmail ? `Depending on your location, you may have the right to access, correct, delete, export or restrict processing of your personal data, and to object to certain processing. To exercise a right, contact ${legalEmail}. We will respond within the timeframe required by applicable law. You may also lodge a complaint with your local data protection authority.` : 'Depending on your location, you may have the right to access, correct, delete, export or restrict processing of your personal data, and to object to certain processing. A public legal mailbox is not currently configured; check the Contact page for the current legal channel. You may also lodge a complaint with your local data protection authority.' },
    ],
  },
  {
    id: 'transfers-security',
    title: 'Transfers and security',
    blocks: [
      { type: 'p', text: 'Our providers may process data in the United States and the European Union. International transfers are governed by applicable law and the transfer mechanisms available under the configured provider agreements.' },
      { type: 'p', text: 'We protect data with encryption in transit, scoped access, and reputable infrastructure providers. No method of transmission or storage is perfectly secure, but we work to protect your information and limit what we collect.' },
    ],
  },
  {
    id: 'children-changes',
    title: 'Children and changes',
    blocks: [
      { type: 'p', text: 'LaunchLog is not directed to children under 16 and we do not knowingly collect their data. If you believe a child has provided us data, contact us and we will remove it.' },
      { type: 'p', text: 'We may update this policy as the product evolves. Material changes will be reflected by the "Last updated" date above, and significant changes will be communicated where appropriate.' },
    ],
  },
]

useSeoMeta({
  title: 'Privacy Policy — LaunchLog',
  description,
  ogTitle: 'Privacy Policy — LaunchLog',
  ogDescription: description,
  ogUrl: pageUrl,
  ogType: 'website',
  twitterTitle: 'Privacy Policy — LaunchLog',
  twitterDescription: description,
})

useHead({
  link: [{ rel: 'canonical', href: pageUrl }],
  script: [
    {
      key: 'launchlog-privacy-schema',
      type: 'application/ld+json',
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        '@id': `${pageUrl}#webpage`,
        url: pageUrl,
        name: 'Privacy Policy — LaunchLog',
        description,
        inLanguage: 'en-US',
        dateModified: '2026-09-01',
        isPartOf: { '@id': `${siteUrl}/#website` },
      }),
    },
  ],
})
</script>

<template>
  <LegalDoc
    eyebrow="Legal"
    title="Privacy Policy"
    intro="We collect as little as possible and never sell your data. Here is exactly what LaunchLog processes, why, and the control you have over it."
    :updated="updated"
    :sections="sections"
    :contact-email="legalEmail"
  />
</template>
